### ISSUE TITLE
Getting "provider doesn't support resource"

### ISSUE THREAD

**Issue by zackhorvath** [prudhvitella/terraform-provider-infoblox#30]
Hi all,

First off - thanks for developing this. Way better than writing a custom python script to do this.

I'm running in to an issue with the latest download version (https://github.com/prudhvitella/terraform-provider-infoblox/releases/tag/pre-release) where I can only use the "infoblox_record" resource type, as when I try to define infoblox_record_host, or etc, I get a "provider doesn't support resource" error.

Is this expected behavior?

Thanks!

**Comment by JackBracken** [comment]
Hiya @zackhorvath 

Looks like you're right, I'm seeing the same one with the version on the release page. I'll check out travis and try to figure out why it didn't push a new release.

**Comment by JackBracken** [comment]
Okay, so silly me. I didn't tag the latest commit as `pre-release` so Travis didn't push a release. I've done that and rebuilding now, I'll comment here when that's finished and I've tested it. Thanks for bringing it to my attention.

**Comment by JackBracken** [comment]
Github seems to be having some serious issues right now. Will try again later.

**Comment by JackBracken** [comment]
Having issues getting Travis to deploy the artifacts from master and I'm not sure why.

Looking through the logs it looks like everything should be fine. Travis clones the repo, checks out the correct commit, sets up a go environment, runs tests, builds, then deploys the built binaries. But the ones on the release page are from an old commit and I have *no idea* why. I'm starting to suspect maybe the old binaries are being cached somewhere; I've even tried deleting the release completely and rebuilding and no dice.

I'll investigate a bit more tonight, but as a workaround in the meantime you could always build the binaries you need for yourself.

**Comment by zackhorvath** [comment]
Thanks for looking into this! I'll look at compiling the binaries on my end and give it a shot.

**Comment by zackhorvath** [comment]
Alright, looks like I'm able to run the new resources after compiling it! Now running into an issue with the count parameter properly passing multiple ip addresses for infloblox_ip.ip, but I think that's operator error :)

**Comment by JackBracken** [comment]
Okay, something funky is going on with travis or I'm just not understanding something.

Looking through the config and the logs, travis:

1. Clones the repo.
2. cd's into the the repo and checks out the commit it wants to build (usually either HEAD or the last commit in a pull request)
3. It sets up a go environment.
4. It runs tests, static analysis etc.
5. It then builds cross-platform binaries using gox.
6. It pushes a release to github using ghr.

Something about 5 or 6 isn't working the way I expect however and either no new build is actually being released to github or it's not actually building the correct one. I have deleted the release and tried restarting a build so my suspicion is that for some reason an old commit is being built? It's odd because it explicitly checks out the correct commit at the very beginning of the build.

sha256 checksums of binaries built on my local machine:

```
ac0b31b36c74dc7d05ced10a9f6270ebf572fb99309b15562775db7d6c04ae0a  darwin_386_terraform-provider-infoblox
36b5c9b843edc2c973c45b2dd703fe6eade2a4a938af1e2c267c99a1963b5ca2  darwin_amd64_terraform-provider-infoblox
cfa8d6f71722fc4fcb35107d728dff74da5c7015d1759285a43230dca76ccf51  linux_386_terraform-provider-infoblox
9288ba8031887ebc9d5b983bb5890afa7ab2ffa4b122d664b1efb1b4b72e64e0  linux_amd64_terraform-provider-infoblox
85a08bf8c48ab3c25026b6bdbc92d0865d203d47e697d0d0cd073f289596271b  linux_arm_terraform-provider-infoblox
ad131439bf477bab4acbcb652696d4e7cd02384553289b5061139d92a9a90178  windows_386_terraform-provider-infoblox.exe
36ddb4f51f1d09bb2334edd8e8f9ea27f9ef07e86c989d5027bd6872190e652a  windows_amd64_terraform-provider-infoblox.exe
```

And the checksums of binaries downloaded from the releases page:

```
ff044f42f4d19e7a70beae37160ed6cb0312c1b670d215521140b4d09e928bfb  darwin_386_terraform-provider-infoblox
9cf487a2ebe16377e935c93152f67b2c861b9ee0b14c0db0011b6599deb88771  darwin_amd64_terraform-provider-infoblox
86ab39a744b6b3d6117ff81e32331611b00afe0cc621336ea24ed020e89f2ffa  linux_386_terraform-provider-infoblox
320e04553982e3456d43144f324aeb3334c180d60aacfdc3655710e6d13ac01d  linux_amd64_terraform-provider-infoblox
d5a33c3736de9116f6fd526bff65ac8d709eacf487ec594fd3f7d92821f2ee6e  linux_arm_terraform-provider-infoblox
326d9d6114f179a45176b8c6d51eb990d5b8e71042fb4df860c3b2a84ae9d532  windows_386_terraform-provider-infoblox.exe
e4f9344c178d9d0e7bdac326323cb1440d6ab44cdcd1fc7b52d4feb87775f473  windows_amd64_terraform-provider-infoblox.exe
```

Possible culprits in my mind from most likely to least likely:

1. Operator error. I'm misunderstanding something pretty fundamental here.
2. The Travis workspace has remnants of an old build somehow? As far as I know Travis workers are ephemeral though I'd be surprised if this were the case.
3. Github is (mistakenly?) caching old builds. I *really* doubt this is happening but pulling straws here.

I'll come back to this but if I can't figure it out we might need to wait for @prudhvitella to save us. :)

**Comment by prudhvitella** [comment]
@JackBracken [Its an issue with golang](https://github.com/golang/go/issues/16860). At the moment, it's not easy to use checksum for verifying build similarity.

**Comment by JackBracken** [comment]
@mbirecki-eis you're a star! That was exactly it. A ```govendor update github.com/prudhvitella/terraform-provider-infoblox/...``` updated the vendor.json and the correct version gets built now. Thanks!
